version: '3.3'

volumes:
  testdata:

services:
  quiz-mysql:
    image: mysql:5.7
    volumes:
      - testdata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootPass
      - MYSQL_DATABASE=databaseName
      - MYSQL_USER=databaseUser
      - MYSQL_PASSWORD=userPassword

  spring-boot-quiz-app:
    image: nxtra/quiz-app
    depends_on:
      - quiz-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=quiz-mysql
      - DATABASE_USER=databaseUser
      - DATABASE_PASSWORD=userPassword
      - DATABASE_NAME=databaseName
      - DATABASE_PORT=3306

  phpmyadmin:
    depends_on:
      - quiz-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3002:80
    environment:
      PMA_HOST: quiz-mysql
      MYSQL_USER: databaseUser
      MYSQL_PASSWORD: userPassword
      MYSQL_ROOT_PASSWORD: rootPass