exam:
  time:
    minutes: 2

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        data:
          jdbc: DEBUG
          jpa: DEBUG
        security: ERROR
        web: ERROR

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

server:
  port: 8090

spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    initialize: true
    password: ''
    url: jdbc:h2:mem:exam;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    format-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false

