logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
        hibernate: INFO

#Datasource
spring:
  datasource:
    url: jdbc:h2:mem:exam;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
    schema: classpath:/schema.sql
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true

#Exam
exam:
  time:
    minutes: 1

#Server
server:
  port: 9000

