exam:
  time:
    minutes: 2

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        data:
          jdbc: DEBUG
          jpa: DEBUG
        security: ERROR
        web: ERROR

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  ignored: /**


server:
  port: 8090

spring:
  security:
    enabled: false
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz
    username: dbtester
    password: ENC(C71GSIu0mO9v3HDM52H9N6O8CL1L1oIr)
  jpa:
    format-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
  algorithm: PBEWITHMD5ANDDES
