exam:
  time:
    minutes: 2


jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
  algorithm: PBEWITHMD5ANDDES

server:
  port: 8080

spring:
  security:
    enabled: false
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz?autoReconnect=true&useSSL=false
    username: dbuser
    password: dbp4ss
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true



